name: rapids-0.17
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20200225.2=he1b5a44_2
  - aiohttp=3.7.3=py37h5e8e339_1
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py37h5e8e339_2
  - arrow-cpp=1.0.1=py37h2318771_14_cuda
  - arrow-cpp-proc=3.0.0=cuda
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - aws-c-common=0.4.59=h36c2ea0_1
  - aws-c-event-stream=0.1.6=had2084c_6
  - aws-checksums=0.1.10=h4e93380_0
  - aws-sdk-cpp=1.8.63=h9b98462_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.3.0=pyh44b312d_0
  - bokeh=2.2.3=py37h89c1867_0
  - boost=1.72.0=py37h48f8a5e_1
  - boost-cpp=1.72.0=h8e57a91_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.4=py37hc58025e_1
  - cfitsio=3.470=hb418390_7
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorcet=2.0.6=pyhd8ed1ab_0
  - cryptography=3.4.4=py37hf1a17b8_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - cudf=0.17.0=cuda_11.0_py37_gf56ef850e6_0
  - cudf_kafka=0.17.0=py37_gf56ef850e6_0
  - cudnn=8.0.0=cuda11.0_0
  - cugraph=0.17.0=py37_gb58e49e8_0
  - cuml=0.17.0=cuda11.0_py37_ga48e0ffbf_0
  - cupy=8.0.0=py37h0ce7dbb_0
  - curl=7.71.1=he644dc0_8
  - cusignal=0.17.0=py38_ge853242_0
  - cuspatial=0.17.0=py37_g897b304_0
  - custreamz=0.17.0=py37_gf56ef850e6_0
  - cuxfilter=0.17.0=py37_g340129d_0
  - cyrus-sasl=2.1.27=h3274739_1
  - cytoolz=0.11.0=py37h5e8e339_3
  - dask=2021.2.0=pyhd8ed1ab_0
  - dask-core=2021.2.0=pyhd8ed1ab_0
  - dask-cuda=0.17.0=py37_0
  - dask-cudf=0.17.0=py37_gf56ef850e6_0
  - datashader=0.11.1=pyh9f0ad1d_0
  - datashape=0.5.4=py_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2021.2.0=py37h89c1867_0
  - dlpack=0.3=he1b5a44_1
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=h9c3ff4c_0
  - faiss-proc=1.0.0=cuda
  - fastavro=1.3.2=py37h5e8e339_0
  - fastrlock=0.5=py37hcd2ae1e_2
  - fiona=1.8.13=py37h0492a4a_1
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.5=h516909a_1002
  - fsspec=0.8.5=pyhd8ed1ab_0
  - future=0.18.2=py37h89c1867_3
  - gdal=3.0.4=py37h4b180d9_10
  - geopandas=0.8.1=py_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h05acad5_0
  - gettext=0.19.8.1=h0b5b191_1005
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.66.7=h9c3ff4c_0
  - glib-tools=2.66.7=h9c3ff4c_0
  - glog=0.4.0=h49b9bf7_3
  - google-cloud-cpp=1.16.0=he4a878c_2
  - google-cloud-cpp-common=0.25.0=he83eced_7
  - googleapis-cpp=0.10.0=h6b1abdc_4
  - graphite2=1.3.13=h58526e2_1001
  - grpc-cpp=1.32.0=h7997a97_1
  - gtest=1.10.0=h4bd325d_7
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf4=4.2.13=h10796ff_1004
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.4.0=py37h89c1867_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - ipykernel=5.4.2=py37h888b3d9_0
  - ipython=7.20.0=py37h888b3d9_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jpype1=1.2.1=py37h2527ec5_0
  - json-c=0.13.1=hbfbb72e_1002
  - jsonschema=3.2.0=py_2
  - jupyter-server-proxy=1.6.0=pyhd8ed1ab_0
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kealib=1.4.14=he4dc956_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcrc32c=1.1.1=h9c3ff4c_2
  - libcudf=0.17.0=cuda11.0_gf56ef850e6_0
  - libcudf_kafka=0.17.0=gf56ef850e6_0
  - libcugraph=0.17.0=cuda11.0_gb58e49e8_0
  - libcuml=0.17.0=cuda11.0_ga48e0ffbf_0
  - libcumlprims=0.17.0=cuda11.0_g8216947_0
  - libcurl=7.71.1=hcdd3856_8
  - libcuspatial=0.17.0=cuda11.0_g897b304_0
  - libdap4=3.20.6=hd7c4107_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libfaiss=1.6.3=h328c4c8_3_cuda
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgcrypt=1.8.7=h36c2ea0_0
  - libgdal=3.0.4=he6a97d6_10
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.66.7=h1f3bc88_0
  - libgomp=9.3.0=h2828fa1_18
  - libgpg-error=1.41=h9c3ff4c_0
  - libgsasl=1.8.0=2
  - libhwloc=2.3.0=h5e5b7d1_1
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=hd79254b_1012
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h255efa7_3
  - libprotobuf=3.13.0.1=h8b12597_0
  - librdkafka=1.5.3=h54cafa9_0
  - librmm=0.17.0=cuda11.0_gc4cc945_0
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_3
  - libspatialite=4.3.0a=h2482549_1038
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libthrift=0.13.0=h5aa387f_6
  - libtiff=4.2.0=hdc55705_0
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.34.0=h516909a_0
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxgboost=1.3.0dev.rapidsai0.17=cuda11.0_0
  - libxml2=2.9.10=hee79883_0
  - llvmlite=0.35.0=py37h9d7f4d0_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=he1b5a44_3
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py37h5e8e339_3
  - mistune=0.8.4=py37h5e8e339_1003
  - msgpack-python=1.0.2=py37h2527ec5_1
  - multidict=5.1.0=py37h5e8e339_1
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - nbclient=0.5.2=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nccl=2.7.8.1=h4962215_100
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - netifaces=0.10.9=py37h5e8e339_1003
  - networkx=2.5=py_0
  - nodejs=13.13.0=hf5d1a2b_0
  - notebook=6.2.0=py37h89c1867_0
  - numba=0.52.0=py37hdc94413_0
  - numpy=1.19.5=py37haa41c4c_1
  - nvtx=0.2.3=py37h5e8e339_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=11.0.8=hacce0ff_0
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1i=h7f98852_0
  - orc=1.6.5=hd3605a7_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.1.5=py37hdc94413_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - panel=0.9.7=py_0
  - param=1.10.1=pyhd3deb0d_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.1=pyhd8ed1ab_0
  - partd=1.1.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickle5=0.0.11=py37h8f50634_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py37h4600e1f_2
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.87.0=h4190859_1
  - poppler-data=0.4.10=0
  - postgresql=12.3=hc2f5b80_3
  - proj=7.0.0=h966b41f_5
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - protobuf=3.13.0.1=py37h745909e_1
  - psutil=5.8.0=py37h5e8e339_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-xgboost=1.3.0dev.rapidsai0.17=cuda11.0py37_0
  - pyarrow=1.0.1=py37hbeecfa9_14_cuda
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydeck=0.5.0=pyh9f0ad1d_0
  - pyee=7.0.4=pyh9f0ad1d_0
  - pygments=2.7.4=pyhd8ed1ab_0
  - pyhive=0.6.3=pyhd3deb0d_0
  - pynvml=8.0.4=py_1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyppeteer=0.2.2=py_1
  - pyproj=2.6.1.post1=py37h34dd122_0
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.9=hffdb5ce_100_cpython
  - python-confluent-kafka=1.5.0=py37h8f50634_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pyviz_comms=2.0.1=pyhd3deb0d_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - pyzmq=22.0.1=py37h499b945_0
  - rapids=0.17.0=cuda11.0_py37_g180f433_165
  - rapids-blazing=0.17.0=cuda11.0_py37_g180f433_165
  - rapids-xgboost=0.17.0=cuda11.0_py37_g180f433_165
  - re2=2020.10.01=he1b5a44_0
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - rmm=0.17.0=cuda_11.0_py37_gc4cc945_0
  - rtree=0.9.7=py37h0b55af0_1
  - sasl=0.2.1=py37h3340039_1002
  - scikit-learn=0.24.1=py37h69acf81_0
  - scipy=1.6.0=py37h14a347d_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37h89c1867_3
  - shapely=1.7.1=py37hba0730f_1
  - simpervisor=0.4=pyhd8ed1ab_0
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - sortedcontainers=2.3.0=pyhd8ed1ab_0
  - spdlog=1.7.0=hc9558a2_2
  - sqlalchemy=1.3.23=py37h5e8e339_0
  - sqlite=3.34.0=h74cdb3f_0
  - streamz=0.6.2=pyh44b312d_0
  - tbb=2020.2=h4bd325d_3
  - tblib=1.6.0=py_0
  - terminado=0.9.2=py37h89c1867_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - thrift=0.13.0=py37h3340039_2
  - thrift_sasl=0.4.2=py37h8f50634_0
  - tiledb=1.7.7=h8efa9f0_3
  - tk=8.6.10=h21135ba_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.56.2=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - treelite=0.93=py37h745909e_3
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzcode=2021a=h7f98852_0
  - ucx=1.8.1+g6b29558=cuda11.0_0
  - ucx-proc=1.0.0=gpu
  - ucx-py=0.17.0=py37_g6b29558_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websockets=8.1=py37h5e8e339_3
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py37h89c1867_4
  - xarray=0.16.2=pyhd8ed1ab_0
  - xerces-c=3.2.2=h8412b87_1004
  - xgboost=1.3.0dev.rapidsai0.17=cuda11.0py37_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py37h5e8e339_1
  - zeromq=4.3.3=h58526e2_3
  - zict=2.0.0=py_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.8=hdf46e1d_0
  - pip:
    - alembic==1.5.4
    - altair==4.1.0
    - astor==0.8.1
    - base58==2.1.0
    - blazingsql==0.17.0
    - blinker==1.4
    - cachetools==4.2.1
    - click-default-group==1.2.2
    - cliff==3.6.0
    - cmaes==0.8.1
    - cmd2==1.5.0
    - colorama==0.4.4
    - colorlog==4.7.2
    - cycler==0.10.0
    - dataclasses-json==0.5.2
    - gitdb==4.0.5
    - gitpython==3.1.13
    - jsonpickle==2.0.0
    - kiwisolver==1.3.1
    - mako==1.1.4
    - marshmallow==3.10.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.3.4
    - more-click==0.0.3
    - mypy-extensions==0.4.3
    - optuna==2.5.0
    - pbr==5.5.1
    - plotly==4.14.3
    - prettytable==0.7.2
    - pykeen==1.3.0
    - pyperclip==1.8.1
    - pystow==0.0.10
    - python-editor==1.0.4
    - pyvis==0.1.8.2
    - retrying==1.3.3
    - sklearn==0.0
    - smmap==3.0.5
    - stevedore==3.3.0
    - streamlit==0.76.0
    - streamlit-agraph==0.0.35
    - streamlit-theme==0.58.0
    - stringcase==1.2.0
    - tabulate==0.8.7
    - toml==0.10.2
    - torch==1.7.1
    - treelite-runtime==0.93
    - typing-inspect==0.6.0
    - tzlocal==2.1
    - validators==0.18.2
    - watchdog==2.0.0
prefix: /home/mughetto/.conda/envs/rapids-0.17
